---

- name: TripleO inventory creation
  hosts: localhost
  gather_facts: no
  pre_tasks:
    - name: Set host
      set_fact:
        host: "{{ other.host }}"

    - name: Set ssh key
      set_fact:
        ssh_key: "{{ other.ssh.key }}"
      when: other.ssh.key

    - name: Set ssh pass
      set_fact:
        ssh_pass: "{{ other.ssh.pass }}"
      when: other.ssh.pass

    - name: Set user
      set_fact:
        user: "{{ other.user }}"

    - name: Set setup type
      set_fact:
        setup_type: "{{ other.setup.type }}"

    - name: Set overcloud user
      set_fact:
        overcloud_user: "{{ other.overcloud.user }}"

    - name: Set venv path
      set_fact:
        venv_path: "{{ other.venv.path }}"

    - name: Set undercloud groups
      set_fact:
        undercloud_groups: "{{ other.undercloud.groups }}"

    - name: Set undercloud only
      set_fact:
        undercloud_only: "{{ other.undercloud.only }}"

    - name: Set hypervisor groups
      set_fact:
        hypervisor_groups: "{{ other.hypervisor.groups }}"

  tasks:
    - name: TripleO Clouds Inventory
      ansible.builtin.import_role:
        name: tripleo_clouds_inventory

    - name: Update Infrared Workspace Inventory
      ansible.builtin.copy:
        src: "{{ environment_dir }}/inventory_{{ host }}"
        dest: "{{ inventory_dir }}/hosts"
      when: inventory_dir is defined
    # - role: inventory-update
      # inventory_file_name: 'tripleo-inventory'
