---

- name: TripleO inventory creation
  hosts: localhost
  gather_facts: no
  tasks:
    - name: TripleO Clouds Inventory
      ansible.builtin.import_role:
        name: tripleo_clouds_inventory

    # After generating a local inventory, link it to current infrared workspace
    # Infrared may override this plugin during execution of other plugins
    - name: Update Infrared Workspace Inventory
      file:
        src: "{{ environment_dir }}/inventory_{{ host }}"
        dest: "{{ inventory_dir }}/hosts"
        state: link
        force: True
